%YAML:1.0
imu: 0
num_of_cam: 2
imu_topic: "/imu0"
image0_topic: "/kitti0/image_raw"
image1_topic: "/kitti1/image_raw"
output_path: "output"
cam0_calib: "cam00-02.yaml"
cam1_calib: "cam00-02.yaml"
image_width: 1241
image_height: 376
use_gpu: 0
use_gpu_acc_flow: 0
use_gpu_ceres: 0
estimate_extrinsic: 0
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1,0,0,0.537165718864418, 0,1,0,0, 0,0,1,0, 0,0,0,1]
multiple_thread: 1
max_cnt: 200
min_dist: 30
freq: 10
F_threshold: 1.0
show_track: 0
flow_back: 1
max_solver_time: 0.08
max_num_iterations: 10
keyframe_parallax: 15
acc_n: 0.1
gyr_n: 0.01
acc_w: 0.001
gyr_w: 1.0e-4
g_norm: 9.81007
estimate_td: 0
td: 0.0
load_previous_pose_graph: 0
pose_graph_save_path: "output/pose_graph/"
save_image: 0
